name: Deploy 

on:
  pull_request:
    branches:
      - 'stable'
  push:
    branches:
      - 'stable'
      
 
jobs:
  test:
  # Making sure this really is...well stable. Deploying a faulty version would be fatal
    name: End 2 End Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
    
     # setup env
      - name: create env
        run: 'echo "$ENV_VALUES" > .env'
        shell: bash
        env:
          ENV_VALUES: ${{secrets.PIPELINE_ENV}}
        
      - name: node modules
        run: 'npm i'
    
      # run unit tests    
      - name: end 2 end tests
        run: npm run test:e2e
        
  docker-push:
    name: Push to docker hub
    runs-on: ubuntu-latest
    needs: [test]
    env:
      REPO: ${{secrets.DOCKER_REPO}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        
      - name: create deploy env
        run: 'echo "$ENV_VALUES" > .env'
        shell: bash
        env:
          ENV_VALUES: ${{secrets.DEPLOY_ENV}}
        
      - name: docker hub login
        run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}
        
      - name: build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .

      - name: Publish docker image
        run: docker push $REPO

  redeploy:
      name: Call redeploy webhook
      runs-on: ubuntu-latest
      needs: [docker-push]
      steps:
        - name: Deploy docker container webhook
          uses: joelwmale/webhook-action@master
          env:
            WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
